### ISSUE TITLE
Please add MangaSee

### ISSUE THREAD

**Issue by kobuki** [anka-213/webcomic_reader#25] opened 2016-06-01 20:55 UTC
Please consider adding http://mangasee.co/

Thanks!

**Comment by anka-213** [comment] 2016-06-02 06:23
@kobuki It should work now. If it doesn't, please reopen this issue. (You might have to tell greasemonkey/tampermonkey to force-update the script.)

**Comment by kobuki** [comment] 2016-06-02 08:51
@anka-213 I force-refreshed it, and can see the new related code but it doesn't work at all. All other supported sites work as usual.

**Comment by anka-213** [comment] 2016-06-02 13:24
@kobuki Hmm. Strange. It works for me. Are you using Firefox or Chrome? Is there any output in the console? Can you paste the url of a page that does not work?

**Comment by kobuki** [comment] 2016-06-02 13:44
@anka-213 Oh, my bad, sorry. I forgot to delete my own custom settings for the site which overrided the new site support code. Works perfectly, thanks!

**Comment by kobuki** [comment] 2016-06-07 22:26
This might warrant a separate issue, but first I'm going to post here. Please close and I add a new ticket if needed.

The site uses a bar on top in the viewer that covers a sizable chunk of the images at the top, sometimes hiding speech bubbles and thus making easy reading hard without scrolling up and down sometimes. Can an option be added to change the viewport size to set a frame for scaling and positioning per site? The current settings can't solve this in a useful way. I can add large borders but then the images become a lot smaller... Not really ideal.

**Comment by anka-213** [comment] 2016-06-08 09:18
Doesn't minimal layout solve the issue?

**Comment by kobuki** [comment] 2016-06-08 09:28
Only half of it. It turns off the site's navbar which forces other quirks on the user for navigating on the site - switching back and forth when reading up/switching between the latest followed chapters, requiring the site navigation tools, for instance. In a certain regard it's better because it actually allows to see the top of the pages, but worse in other aspects.

**Comment by anka-213** [comment] 2016-06-08 09:35
I can:

a) Add the navbar to the extras, so you can find it below the comic. (so minimal mode works)
b) Add some css for the site so that the navbar is no longer hovering (i.e. scrolls with the page instead of staying with at the top) and thus no longer covers the comic.
or
c) Try to fix so it scrolls to the correct place while keeping the navbar hovering.

Which would you prefer?

**Comment by anka-213** [comment] 2016-06-08 09:36
("a" is probably easiest)

**Comment by kobuki** [comment] 2016-06-08 09:39
Hm, yeah, I figured a) would be probably the simplest, though I'd personally prefer b) -- this is what the site should have done originally :\ Most sites work like that.

**Comment by anka-213** [comment] 2016-06-08 09:41
C is hardest, so I'm glad you didn't pick that. ;)
I'll give b a shot, it shouldn't be too hard.

**Comment by kobuki** [comment] 2016-06-08 09:41
Wonderful support we have here, thanks ;)

**Comment by anka-213** [comment] 2016-06-08 10:01
Haha, thanks. (^○^)

**Comment by anka-213** [comment] 2016-06-08 10:04
I threw in "a" as well, as a bonus, since it was almost no effort at all ;)

**Comment by kobuki** [comment] 2016-06-08 10:29
Nice, working great! Ghostery interferes with the new change (images get shifted down by ~12px) but that's not the script's fault at all.

**Comment by kobuki** [comment] 2016-07-06 21:29
The script stopped working... The first image is correctly resized and positioned but it's impossible to go next/back with the green arrows. See for example: http://mangasee.co/manga/?series=PlatinumEnd&chapter=8&index=1&page=1

**Comment by Tmp341** [comment] 2016-07-07 19:19
it's working for me, even though i have ghostery.

**Comment by kobuki** [comment] 2016-07-07 21:10
Hmm, weird. Now it does work for me too. It was broken for a few days, though. Not necessarily the script - the site went through several small changes recently. Maybe that. Ah, well.

**Comment by kobuki** [comment] 2016-07-13 23:08
OK, it works only for the few pages of any manga. Then it indefinitely shows the hourglass instead of the roght arrow. If I do several page refreshes, it continues to work for some chapter images and then the same issue again. All other sites I frequent do work flawlessly, this is the only one exhibiting the problem. Tried in FF 47.0.1 and Chrome 51.0.2704.106. Maybe something about image prefetch?

**Comment by Tmp341** [comment] 2016-07-14 02:55
I got something weird on FF 48.0b6. I've tried a random manga, it worked 4 or 5 pages. Then script stopped showing arrow and then my mouse cursor changed to it's loading animation. Until i change the page from the menu, nothing happens.

**Comment by kobuki** [comment] 2016-07-14 08:15
Thanks for reporting this, it seems it's not only on my setup then.

**Comment by Tmp341** [comment] 2016-07-15 03:34
It seems my problem isn't occuring anymore.  Last night, i've done a deep cleaning with CCleaner. Today, i've finished a chapter without a problem.

**Comment by kobuki** [comment] 2016-07-15 11:34
No change here. Problem persists in both Firefox and Chrome as well.

**Comment by anka-213** [comment] 2016-07-15 12:34
Do you get any error messages in the console?

>

**Comment by kobuki** [comment] 2016-07-15 12:58
None I can make sense of. Some CORS errors. Attached is a console copypasta.

[console.txt](https://github.com/anka-213/webcomic_reader/files/365977/console.txt)

**Comment by anka-213** [comment] 2016-07-28 21:11
From looking at the log, it seems like the problem is that it tries to go from the domain mangasee.co to a1.mangasee.co. The script doesn't work accross domains, because the browser blocks cross domain requests (CORS). I'll take a look at what causes it.

**Comment by anka-213** [comment] 2016-08-29 20:09
Oops, wrong bug number

**Comment by kobuki** [comment] 2016-08-29 20:11
LOL, well, it seems that the problem solved itself in the meantime. Now it works properly as before. They probably changed something in the page's code 1-2 weeks ago. Please don't close this yet - let's allow others to comment for a while. Thanks!

**Comment by anka-213** [comment] 2016-08-29 20:13
Nice. :D

You can still comment on closed issues, but sure, I'll leave it open for a while if you want.

**Comment by anka-213** [comment] 2016-09-02 22:16
I'll close this now. If the site stops working again, you can always open a new issue.

**Closed by anka-213** 2016-09-02 22:16 UTC
Labels: bug, site request
